### ISSUE TITLE
Always execute the extension on scrolling.

### ISSUE THREAD

**Issue by Aqa-Ib** [Jay-rO-o/center-cursor#1]
Hello, is there a way for this extension to execute every time I scroll the editor?
Thank you.

**Comment by Aqa-Ib** [comment]
Alright, I need to implement the event onDidChangeNotebookEditorVisibleRanges. That is what I was looking for. When I have the time I will develop it. Cheers.

**Comment by JayBluem** [comment]
@Aqa-Ib 
First of all thank you so much for using this extension.  
Sentences can be awkward because I'm using a translator.  
The reason why I didn't run it every time I scrolled is because vscode remembers the cursor position whenever the cursor moves (I often want to go back to the previous cursor).  
But, there is a way. Add an option to run it every time scrolling.  
And as a result of searching the vscode api, I think you can use  `onDidChangeTextEditorVisibleRanges: Event<TextEditorVisibleRangesChangeEvent>`.  
Thank you.

**Comment by Aqa-Ib** [comment]
Thank you very much!
